/*
Navicat MySQL Data Transfer

Source Server         : MySQL
Source Server Version : 50710
Source Host           : localhost:3307
Source Database       : jiansuo

Target Server Type    : MYSQL
Target Server Version : 50710
File Encoding         : 65001

Date: 2019-03-30 13:29:20
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for copy
-- ----------------------------
DROP TABLE IF EXISTS `copy`;
CREATE TABLE `copy` (
  `id` int(4) NOT NULL AUTO_INCREMENT,
  `yuan_id` int(4) DEFAULT NULL,
  `copy_field` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `start_position` int(4) DEFAULT NULL,
  `last_position` int(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=386 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of copy
-- ----------------------------
INSERT INTO `copy` VALUES ('1', '7', '（Augmented Reality，简称', 'https://baike.baidu.com/item/AR', '4', '24');
INSERT INTO `copy` VALUES ('2', '7', '摄影机影像的位置', 'https://baike.baidu.com/item/AR', '63', '70');
INSERT INTO `copy` VALUES ('3', '9', '（ICP）、企业、媒体和各类网站', 'https://baike.baidu.com/item/IDC', '17', '32');
INSERT INTO `copy` VALUES ('4', '9', '间租用、网络批发带宽以及ASP、EC', 'https://baike.baidu.com/item/IDC', '50', '67');
INSERT INTO `copy` VALUES ('5', '9', '安全运作的基础设施，也', 'https://baike.baidu.com/item/IDC', '100', '110');
INSERT INTO `copy` VALUES ('6', '9', '分销商、供应商、客户等）实施价值链管理的', 'https://baike.baidu.com/item/IDC', '124', '143');
INSERT INTO `copy` VALUES ('7', '9', '传输服务和高速接入服务', 'https://baike.baidu.com/item/IDC', '185', '195');
INSERT INTO `copy` VALUES ('8', '9', '综合全面的解决方案', 'https://baike.baidu.com/item/IDC', '202', '210');
INSERT INTO `copy` VALUES ('9', '11', '办公自动化（Office Automation，简称', 'https://baike.baidu.com/item/办公自动化', '0', '25');
INSERT INTO `copy` VALUES ('10', '11', '办公自动化（Office Automation，简称', 'https://baike.baidu.com/item/OA', '0', '25');
INSERT INTO `copy` VALUES ('11', '11', 'utomation', 'https://baike.baidu.com/item/自动化', '14', '22');
INSERT INTO `copy` VALUES ('12', '12', 'erprise ', 'https://baike.baidu.com/item/ERP', '10', '17');
INSERT INTO `copy` VALUES ('13', '12', '提出。企业资源计划', 'https://baike.baidu.com/item/ERP', '72', '80');
INSERT INTO `copy` VALUES ('14', '12', '在信息技术基础上', 'https://baike.baidu.com/item/ERP', '149', '156');
INSERT INTO `copy` VALUES ('15', '12', '为企业决策层及员工提供决策运行手段的管理平台。', 'https://baike.baidu.com/item/ERP', '166', '188');
INSERT INTO `copy` VALUES ('16', '14', 'nternet Protocol, ', 'https://baike.baidu.com/item/网际协议', '46', '63');
INSERT INTO `copy` VALUES ('17', '19', '环保节能的居住环境。', 'https://baike.baidu.com/item/智能家居', '103', '112');
INSERT INTO `copy` VALUES ('18', '22', 'line To Offline', 'https://baike.baidu.com/item/O2O', '6', '20');
INSERT INTO `copy` VALUES ('19', '22', '指将线下的商务机会与', 'https://baike.baidu.com/item/O2O', '38', '47');
INSERT INTO `copy` VALUES ('20', '22', '联网结合，让互联网成为线下交易的平台', 'https://baike.baidu.com/item/O2O', '51', '68');
INSERT INTO `copy` VALUES ('21', '22', ',可以通称为O2O。', 'https://baike.baidu.com/item/O2O', '90', '99');
INSERT INTO `copy` VALUES ('22', '22', '本地化及移动设备', 'https://baike.baidu.com/item/O2O', '121', '128');
INSERT INTO `copy` VALUES ('23', '22', 'line To Offline', 'https://baike.baidu.com/item/ 线下', '6', '20');
INSERT INTO `copy` VALUES ('24', '22', '指将线下的商务机会与', 'https://baike.baidu.com/item/ 线下', '38', '47');
INSERT INTO `copy` VALUES ('25', '22', '联网结合，让互联网成为线下交易的平台', 'https://baike.baidu.com/item/ 线下', '51', '68');
INSERT INTO `copy` VALUES ('26', '22', ',可以通称为O2O。', 'https://baike.baidu.com/item/ 线下', '90', '99');
INSERT INTO `copy` VALUES ('27', '22', '本地化及移动设备', 'https://baike.baidu.com/item/ 线下', '121', '128');
INSERT INTO `copy` VALUES ('28', '41', 'Availability', 'https://baike.baidu.com/item/保密性', '382', '393');
INSERT INTO `copy` VALUES ('29', '47', 'adio Frequency', 'https://baike.baidu.com/item/射频', '8', '21');
INSERT INTO `copy` VALUES ('30', '47', 'adio Frequency', 'https://baike.baidu.com/item/RFID', '8', '21');
INSERT INTO `copy` VALUES ('31', '47', 'Identification', 'https://baike.baidu.com/item/RFID', '22', '35');
INSERT INTO `copy` VALUES ('32', '47', '无线射频识别，是一种', 'https://baike.baidu.com/item/RFID', '47', '56');
INSERT INTO `copy` VALUES ('33', '47', '系统与特定目标之间建立机械或光学接触。', 'https://baike.baidu.com/item/RFID', '96', '114');
INSERT INTO `copy` VALUES ('34', '50', '遥感（remote sensing）是指', 'https://baike.baidu.com/item/遥感', '0', '19');
INSERT INTO `copy` VALUES ('35', '51', 'Wireless ', 'https://baike.baidu.com/item/无线通信', '8', '16');
INSERT INTO `copy` VALUES ('36', '51', '无线传感器网络(Wireless Sensor Networks, ', 'https://baike.baidu.com/item/WSN', '0', '33');
INSERT INTO `copy` VALUES ('37', '51', ')是一种分布式传感网络，', 'https://baike.baidu.com/item/WSN', '40', '51');
INSERT INTO `copy` VALUES ('38', '51', '的末梢是可以感知和检查外部世界的传感器。WSN中的传感器通过无线方式通信，因此网络设置灵活，设备位置可以', 'https://baike.baidu.com/item/WSN', '74', '125');
INSERT INTO `copy` VALUES ('39', '51', '还可以跟互联网进行有线或无线方式的连接。', 'https://baike.baidu.com/item/WSN', '131', '150');
INSERT INTO `copy` VALUES ('40', '51', 'WSN的发展得益于', 'https://baike.baidu.com/item/WSN', '151', '159');
INSERT INTO `copy` VALUES ('41', '51', '微机电系统(Micro-Electro-Mechanism System, MEMS)、', 'https://baike.baidu.com/item/WSN', '160', '203');
INSERT INTO `copy` VALUES ('42', '51', '片上系统(System on Chip, SoC)、无线通信和低功耗', 'https://baike.baidu.com/item/WSN', '204', '237');
INSERT INTO `copy` VALUES ('43', '51', '嵌入式技术的飞速发展。', 'https://baike.baidu.com/item/WSN', '238', '248');
INSERT INTO `copy` VALUES ('44', '51', 'WSN广泛应用于军事、智能交通、环境监控、医疗卫生等多个领域。', 'https://baike.baidu.com/item/WSN', '249', '279');
INSERT INTO `copy` VALUES ('45', '53', '-3600MHz', 'https://baike.baidu.com/item/5G', '1126', '1133');
INSERT INTO `copy` VALUES ('46', '53', '2017年12月21日，在国际电信标准组织3GPP RAN第78次全体会议上，5G NR首发版本正式冻结并发布。', 'https://baike.baidu.com/item/5G', '1249', '1304');
INSERT INTO `copy` VALUES ('47', '53', '2017年12月', 'https://baike.baidu.com/item/5G', '1249', '1256');
INSERT INTO `copy` VALUES ('48', '53', '月1日，韩国三大运营商SK、KT与LG U+同步在韩国部分地区推出5G服务，这也是新一代移动通信服务在全球首次实现商用。', 'https://baike.baidu.com/item/5G', '2106', '2165');
INSERT INTO `copy` VALUES ('49', '53', '日，工信部同意联通集团自通知日至2020年6月30日使用3500MHz-3600MHz频率', 'https://baike.baidu.com/item/5G', '2269', '2313');
INSERT INTO `copy` VALUES ('50', '53', '正式对外公布，已向中国电信、中国移动、中国联通发放了5G系统中低频段试验频率使用许可', 'https://baike.baidu.com/item/5G', '2348', '2389');
INSERT INTO `copy` VALUES ('51', '59', '特指基于高可用系统中的两台服务器的热备', 'https://baike.baidu.com/item/热备', '18', '36');
INSERT INTO `copy` VALUES ('52', '81', 'lockchain', 'https://baike.baidu.com/item/区块', '17', '25');
INSERT INTO `copy` VALUES ('53', '81', 'lockchain', 'https://baike.baidu.com/item/区块', '17', '25');
INSERT INTO `copy` VALUES ('54', '81', 'lockchain', 'https://baike.baidu.com/item/区块', '17', '25');
INSERT INTO `copy` VALUES ('55', '81', 'lockchain', 'https://baike.baidu.com/item/ 哪几', '17', '25');
INSERT INTO `copy` VALUES ('56', '81', 'lockchain', 'https://baike.baidu.com/item/ 哪几', '17', '25');
INSERT INTO `copy` VALUES ('57', '81', 'lockchain', 'https://baike.baidu.com/item/ 哪几', '17', '25');
INSERT INTO `copy` VALUES ('58', '100', 'nfrastructure', 'https://baike.baidu.com/item/基础设施', '123', '135');
INSERT INTO `copy` VALUES ('59', '104', 'CPS,Cyber-Physical Systems', 'https://baike.baidu.com/item/CPS', '7', '32');
INSERT INTO `copy` VALUES ('60', '104', '是一个综合计算、网络和物理环境的多维复杂系统，通过', 'https://baike.baidu.com/item/CPS', '34', '58');
INSERT INTO `copy` VALUES ('61', '104', 'unication、Control', 'https://baike.baidu.com/item/CPS', '125', '141');
INSERT INTO `copy` VALUES ('62', '104', '技术的有机融合与深度协作，实现大型工程系统的实时感知、动态控制和信息服务。CPS', 'https://baike.baidu.com/item/CPS', '143', '182');
INSERT INTO `copy` VALUES ('63', '110', '恶意的原因而遭到', 'https://baike.baidu.com/item/信息安全', '48', '55');
INSERT INTO `copy` VALUES ('64', '110', '授权拷贝和所寄生系统的安全性。信息安全', 'https://baike.baidu.com/item/信息安全', '102', '120');
INSERT INTO `copy` VALUES ('65', '111', '网络安全是指网络系统的', 'https://baike.baidu.com/item/网络安全', '0', '10');
INSERT INTO `copy` VALUES ('66', '111', '及其系统中的数据受到保护，不因偶然的或者恶意的原因而遭', 'https://baike.baidu.com/item/网络安全', '16', '42');
INSERT INTO `copy` VALUES ('67', '111', '网络服务不中断。', 'https://baike.baidu.com/item/网络安全', '67', '74');
INSERT INTO `copy` VALUES ('68', '111', '然的或者恶意的原因而遭到', 'https://baike.baidu.com/item/信息安全', '32', '43');
INSERT INTO `copy` VALUES ('69', '112', '击包含攻击者访问', 'https://baike.baidu.com/item/主动攻击', '110', '117');
INSERT INTO `copy` VALUES ('70', '112', '所需信息的故意行为。比如', 'https://baike.baidu.com/item/主动攻击', '118', '129');
INSERT INTO `copy` VALUES ('71', '112', '地址去连接服务器，使接受到错误 IP', 'https://baike.baidu.com/item/主动攻击', '138', '155');
INSERT INTO `copy` VALUES ('72', '112', '的系统浪费时间去连接', 'https://baike.baidu.com/item/主动攻击', '159', '168');
INSERT INTO `copy` VALUES ('73', '112', '远程登录到指定机器的端口', 'https://baike.baidu.com/item/主动攻击', '177', '188');
INSERT INTO `copy` VALUES ('74', '112', '邮件服务器的信息', 'https://baike.baidu.com/item/主动攻击', '197', '204');
INSERT INTO `copy` VALUES ('75', '112', '击包含攻击者访问', 'https://baike.baidu.com/item/类型区', '110', '117');
INSERT INTO `copy` VALUES ('76', '112', '所需信息的故意行为。比如', 'https://baike.baidu.com/item/类型区', '118', '129');
INSERT INTO `copy` VALUES ('77', '112', '地址去连接服务器，使接受到错误 IP', 'https://baike.baidu.com/item/类型区', '138', '155');
INSERT INTO `copy` VALUES ('78', '112', '的系统浪费时间去连接', 'https://baike.baidu.com/item/类型区', '159', '168');
INSERT INTO `copy` VALUES ('79', '112', '远程登录到指定机器的端口', 'https://baike.baidu.com/item/类型区', '177', '188');
INSERT INTO `copy` VALUES ('80', '112', '邮件服务器的信息', 'https://baike.baidu.com/item/类型区', '197', '204');
INSERT INTO `copy` VALUES ('81', '112', '击包含攻击者访问', 'https://baike.baidu.com/item/ 系统', '110', '117');
INSERT INTO `copy` VALUES ('82', '112', '所需信息的故意行为。比如', 'https://baike.baidu.com/item/ 系统', '118', '129');
INSERT INTO `copy` VALUES ('83', '112', '地址去连接服务器，使接受到错误 IP', 'https://baike.baidu.com/item/ 系统', '138', '155');
INSERT INTO `copy` VALUES ('84', '112', '的系统浪费时间去连接', 'https://baike.baidu.com/item/ 系统', '159', '168');
INSERT INTO `copy` VALUES ('85', '112', '远程登录到指定机器的端口', 'https://baike.baidu.com/item/ 系统', '177', '188');
INSERT INTO `copy` VALUES ('86', '112', '邮件服务器的信息', 'https://baike.baidu.com/item/ 系统', '197', '204');
INSERT INTO `copy` VALUES ('87', '121', '密钥：公开密钥（', 'https://baike.baidu.com/item/公开密钥', '11', '18');
INSERT INTO `copy` VALUES ('88', '122', '发送者才能产生的别人无法伪造的一段数字串，这段数字串同时也', 'https://baike.baidu.com/item/数字签名', '41', '69');
INSERT INTO `copy` VALUES ('89', '122', '性的一个有效证明。', 'https://baike.baidu.com/item/数字签名', '87', '95');
INSERT INTO `copy` VALUES ('90', '123', '程序中插入的破坏计算机功能或者', 'https://baike.baidu.com/item/病毒', '14', '28');
INSERT INTO `copy` VALUES ('91', '123', '计算机指令或者程序', 'https://baike.baidu.com/item/病毒', '50', '58');
INSERT INTO `copy` VALUES ('92', '123', '程序中插入的破坏计算机功能或者', 'https://baike.baidu.com/item/计算机病毒', '14', '28');
INSERT INTO `copy` VALUES ('93', '123', '计算机指令或者程序', 'https://baike.baidu.com/item/计算机病毒', '50', '58');
INSERT INTO `copy` VALUES ('94', '148', 'nial of ', 'https://baike.baidu.com/item/拒绝服务', '9', '16');
INSERT INTO `copy` VALUES ('95', '149', 'istributed', 'https://baike.baidu.com/item/DDoS', '11', '20');
INSERT INTO `copy` VALUES ('96', '151', 'ntrusion Detection System', 'https://baike.baidu.com/item/IDS', '8', '32');
INSERT INTO `copy` VALUES ('97', '163', 'nial of ', 'https://baike.baidu.com/item/拒绝服务', '9', '16');
INSERT INTO `copy` VALUES ('98', '166', 'ntrusion Detection System', 'https://baike.baidu.com/item/IDS', '8', '32');
INSERT INTO `copy` VALUES ('99', '180', '的现代化智能电子设备', 'https://baike.baidu.com/item/计算机', '39', '48');
INSERT INTO `copy` VALUES ('100', '180', '的现代化智能电子设备', 'https://baike.baidu.com/item/算机', '39', '48');
INSERT INTO `copy` VALUES ('101', '182', '软件（中国大陆及香港用语，台湾称作', 'https://baike.baidu.com/item/软件', '0', '16');
INSERT INTO `copy` VALUES ('102', '182', 'Software）是一系列按照特定顺序组织的计算机数据和', 'https://baike.baidu.com/item/软件', '23', '50');
INSERT INTO `copy` VALUES ('103', '182', '说软件就是程序加文档的集合体。', 'https://baike.baidu.com/item/软件', '111', '125');
INSERT INTO `copy` VALUES ('104', '182', '般来讲软件被划分为', 'https://baike.baidu.com/item/软件', '127', '135');
INSERT INTO `copy` VALUES ('105', '182', '系统软件、应用软件和介于这两者之间的', 'https://baike.baidu.com/item/软件', '136', '153');
INSERT INTO `copy` VALUES ('106', '183', '软件开发是根据用户要求建造出', 'https://baike.baidu.com/item/软件开发', '0', '13');
INSERT INTO `copy` VALUES ('107', '183', '软件系统或者系统中的软件部分的过程', 'https://baike.baidu.com/item/软件开发', '14', '30');
INSERT INTO `copy` VALUES ('108', '183', '需求分析、设计、实现和测试', 'https://baike.baidu.com/item/软件开发', '40', '52');
INSERT INTO `copy` VALUES ('109', '187', '算法（Algorithm）是指解', 'https://baike.baidu.com/item/算法', '0', '15');
INSERT INTO `copy` VALUES ('110', '187', '的准确而完整的描述，', 'https://baike.baidu.com/item/算法', '19', '28');
INSERT INTO `copy` VALUES ('111', '187', '表着用系统的方法描述解决问题的策略机制。', 'https://baike.baidu.com/item/算法', '64', '83');
INSERT INTO `copy` VALUES ('112', '191', 'erating ', 'https://baike.baidu.com/item/操作系统', '7', '14');
INSERT INTO `copy` VALUES ('113', '191', '定系统资源供需的优先次序、控制输入与输出设备、操作', 'https://baike.baidu.com/item/操作系统', '76', '100');
INSERT INTO `copy` VALUES ('114', '191', '等基本事务。操作系统', 'https://baike.baidu.com/item/操作系统', '118', '127');
INSERT INTO `copy` VALUES ('115', '191', '提供一个让用户与系统交互的操作界面。', 'https://baike.baidu.com/item/操作系统', '128', '145');
INSERT INTO `copy` VALUES ('116', '192', 'erating ', 'https://baike.baidu.com/item/操作系统', '22', '29');
INSERT INTO `copy` VALUES ('117', '192', '是一个强大的多用户、多任务', 'https://baike.baidu.com/item/Unix', '236', '248');
INSERT INTO `copy` VALUES ('118', '192', '早由KenThompson、Dennis Ritchie和Douglas McIlroy于1969年在', 'https://baike.baidu.com/item/Unix', '266', '316');
INSERT INTO `copy` VALUES ('119', '192', '贝尔实验室开发。', 'https://baike.baidu.com/item/Unix', '322', '329');
INSERT INTO `copy` VALUES ('120', '192', 'Macintosh', 'https://baike.baidu.com/item/Mac', '460', '468');
INSERT INTO `copy` VALUES ('121', '192', 'icrosoft Windows', 'https://baike.baidu.com/item/DOS', '114', '129');
INSERT INTO `copy` VALUES ('122', '193', 'Microsoft Windows', 'https://baike.baidu.com/item/Microsoft', '0', '16');
INSERT INTO `copy` VALUES ('123', '193', 'Microsoft', 'https://baike.baidu.com/item/Microsoft', '0', '8');
INSERT INTO `copy` VALUES ('124', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('125', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('126', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('127', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('128', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('129', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('130', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('131', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('132', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('133', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('134', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('135', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('136', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('137', '193', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '235', '242');
INSERT INTO `copy` VALUES ('138', '193', 'Microsoft Windows', 'https://baike.baidu.com/item/Windows', '0', '16');
INSERT INTO `copy` VALUES ('139', '193', '微软公司研发的一套操作系统，它问世于1985年，起初仅仅是', 'https://baike.baidu.com/item/Windows', '21', '49');
INSERT INTO `copy` VALUES ('140', '193', 'Microsoft-', 'https://baike.baidu.com/item/Windows', '50', '59');
INSERT INTO `copy` VALUES ('141', '193', 'DOS模拟环境，后续的系统版本由于微软不断的更新升级，不但易用，也慢慢的成为家家户户人们最喜爱的操作系统。', 'https://baike.baidu.com/item/Windows', '60', '112');
INSERT INTO `copy` VALUES ('142', '193', 'Windows采用了图形化模式', 'https://baike.baidu.com/item/Windows', '113', '127');
INSERT INTO `copy` VALUES ('143', '193', 'GUI，比起从前的', 'https://baike.baidu.com/item/Windows', '128', '136');
INSERT INTO `copy` VALUES ('144', '193', 'DOS需要键入指令使用的方式更为人性化。随着电脑硬件和软件的不断升级，微软的Windows也在不断升级，从架构的16位、16+32位混合版（Windows9x）、', 'https://baike.baidu.com/item/Windows', '137', '217');
INSERT INTO `copy` VALUES ('145', '193', '系统版本从最初的', 'https://baike.baidu.com/item/Windows', '227', '234');
INSERT INTO `copy` VALUES ('146', '193', 'Windows 1.0 到大家熟知的', 'https://baike.baidu.com/item/Windows', '235', '252');
INSERT INTO `copy` VALUES ('147', '193', 'Windows 95、', 'https://baike.baidu.com/item/Windows', '253', '263');
INSERT INTO `copy` VALUES ('148', '193', 'Windows 98、', 'https://baike.baidu.com/item/Windows', '264', '274');
INSERT INTO `copy` VALUES ('149', '193', 'Windows ME、', 'https://baike.baidu.com/item/Windows', '275', '285');
INSERT INTO `copy` VALUES ('150', '193', 'Windows 2000、', 'https://baike.baidu.com/item/Windows', '286', '298');
INSERT INTO `copy` VALUES ('151', '193', 'Windows 2003', 'https://baike.baidu.com/item/Windows', '299', '310');
INSERT INTO `copy` VALUES ('152', '193', 'Windows XP、', 'https://baike.baidu.com/item/Windows', '312', '322');
INSERT INTO `copy` VALUES ('153', '193', 'Windows Vista、', 'https://baike.baidu.com/item/Windows', '323', '336');
INSERT INTO `copy` VALUES ('154', '193', 'Windows 7、', 'https://baike.baidu.com/item/Windows', '337', '346');
INSERT INTO `copy` VALUES ('155', '193', 'Windows 8、', 'https://baike.baidu.com/item/Windows', '347', '356');
INSERT INTO `copy` VALUES ('156', '193', 'Windows 8.1、', 'https://baike.baidu.com/item/Windows', '357', '368');
INSERT INTO `copy` VALUES ('157', '193', 'Windows 10和 Windows Server服务器企业级操作系统，不断持续更新，微软一直在致力于Windows操作系统的开发和完善。现在最新的正式版本是Windows 10', 'https://baike.baidu.com/item/Windows', '369', '458');
INSERT INTO `copy` VALUES ('158', '193', 'Microsoft Windows', 'https://baike.baidu.com/item/微软', '0', '16');
INSERT INTO `copy` VALUES ('159', '193', 'Microsoft', 'https://baike.baidu.com/item/微软', '0', '8');
INSERT INTO `copy` VALUES ('160', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('161', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('162', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('163', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('164', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('165', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('166', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('167', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('168', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('169', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('170', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('171', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('172', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('173', '193', 'Windows ', 'https://baike.baidu.com/item/微软', '235', '242');
INSERT INTO `copy` VALUES ('174', '194', '采用了图形化模式', 'https://baike.baidu.com/item/Windows', '23', '30');
INSERT INTO `copy` VALUES ('175', '195', 'UNIX操作系统', 'https://baike.baidu.com/item/UNIX', '0', '7');
INSERT INTO `copy` VALUES ('176', '195', '，是一个强大的多用户、多任务', 'https://baike.baidu.com/item/UNIX', '8', '21');
INSERT INTO `copy` VALUES ('177', '195', '操作系统，支持多种', 'https://baike.baidu.com/item/UNIX', '22', '30');
INSERT INTO `copy` VALUES ('178', '195', '处理器架构，按照操作系统的分类，属于', 'https://baike.baidu.com/item/UNIX', '31', '48');
INSERT INTO `copy` VALUES ('179', '195', 'UNIX操作系统', 'https://baike.baidu.com/item/Unix', '0', '7');
INSERT INTO `copy` VALUES ('180', '195', '，是一个强大的多用户、多任务', 'https://baike.baidu.com/item/Unix', '8', '21');
INSERT INTO `copy` VALUES ('181', '195', '操作系统，支持多种', 'https://baike.baidu.com/item/Unix', '22', '30');
INSERT INTO `copy` VALUES ('182', '195', '处理器架构，按照操作系统的分类，属于', 'https://baike.baidu.com/item/Unix', '31', '48');
INSERT INTO `copy` VALUES ('183', '197', '苹果公司自行开发', 'https://baike.baidu.com/item/macOS', '10', '17');
INSERT INTO `copy` VALUES ('184', '197', '电脑上的操作系统。Mac', 'https://baike.baidu.com/item/macOS', '37', '48');
INSERT INTO `copy` VALUES ('185', '197', '内核的图形化操作系统', 'https://baike.baidu.com/item/macOS', '58', '67');
INSERT INTO `copy` VALUES ('186', '197', '一般情况下在普通', 'https://baike.baidu.com/item/macOS', '79', '86');
INSERT INTO `copy` VALUES ('187', '197', '最新的系统版本是macOS 10.14', 'https://baike.baidu.com/item/macOS', '98', '116');
INSERT INTO `copy` VALUES ('188', '197', ' ，且网上也有在PC上运行的Mac系统，简称 Mac PC。', 'https://baike.baidu.com/item/macOS', '117', '146');
INSERT INTO `copy` VALUES ('189', '197', '另外，疯狂肆虐的', 'https://baike.baidu.com/item/macOS', '147', '154');
INSERT INTO `copy` VALUES ('190', '197', '电脑病毒几乎都是针对Windows的，由于MAC的架构与', 'https://baike.baidu.com/item/macOS', '155', '182');
INSERT INTO `copy` VALUES ('191', '197', 'Windows不同，', 'https://baike.baidu.com/item/macOS', '183', '192');
INSERT INTO `copy` VALUES ('192', '197', 'Windows的', 'https://baike.baidu.com/item/运行', '165', '172');
INSERT INTO `copy` VALUES ('193', '197', ' Macintosh', 'https://baike.baidu.com/item/Mac', '24', '33');
INSERT INTO `copy` VALUES ('194', '198', 'pp Store', 'https://baike.baidu.com/item/macOS', '129', '136');
INSERT INTO `copy` VALUES ('195', '199', 'Microsoft ', 'https://baike.baidu.com/item/Excel', '0', '9');
INSERT INTO `copy` VALUES ('196', '199', 'Microsoft', 'https://baike.baidu.com/item/Excel', '0', '8');
INSERT INTO `copy` VALUES ('197', '199', 'icrosoft ', 'https://baike.baidu.com/item/Excel', '1', '9');
INSERT INTO `copy` VALUES ('198', '199', 'Microsoft ', 'https://baike.baidu.com/item/ 办公', '0', '9');
INSERT INTO `copy` VALUES ('199', '199', 'Microsoft', 'https://baike.baidu.com/item/ 办公', '0', '8');
INSERT INTO `copy` VALUES ('200', '199', 'icrosoft ', 'https://baike.baidu.com/item/ 办公', '1', '9');
INSERT INTO `copy` VALUES ('201', '199', 'Microsoft Office是', 'https://baike.baidu.com/item/Office', '0', '16');
INSERT INTO `copy` VALUES ('202', '199', 'icrosoft ', 'https://baike.baidu.com/item/Office', '1', '9');
INSERT INTO `copy` VALUES ('203', '199', 'Windows ', 'https://baike.baidu.com/item/Office', '47', '54');
INSERT INTO `copy` VALUES ('204', '199', '用组件有 Word、', 'https://baike.baidu.com/item/Office', '70', '79');
INSERT INTO `copy` VALUES ('205', '199', 't等。最新版本为', 'https://baike.baidu.com/item/Office', '96', '103');
INSERT INTO `copy` VALUES ('206', '199', 'Office 365(', 'https://baike.baidu.com/item/Office', '104', '114');
INSERT INTO `copy` VALUES ('207', '199', 'Office 2019)。', 'https://baike.baidu.com/item/Office', '115', '127');
INSERT INTO `copy` VALUES ('208', '199', 'icrosoft ', 'https://baike.baidu.com/item/Office', '1', '9');
INSERT INTO `copy` VALUES ('209', '199', 'icrosoft ', 'https://baike.baidu.com/item/Office', '1', '9');
INSERT INTO `copy` VALUES ('210', '199', 'Microsoft Office', 'https://baike.baidu.com/item/Word', '0', '15');
INSERT INTO `copy` VALUES ('211', '199', 'crosoft Windows ', 'https://baike.baidu.com/item/Word', '39', '54');
INSERT INTO `copy` VALUES ('212', '199', 'crosoft ', 'https://baike.baidu.com/item/Word', '2', '9');
INSERT INTO `copy` VALUES ('213', '199', 'crosoft ', 'https://baike.baidu.com/item/Word', '2', '9');
INSERT INTO `copy` VALUES ('214', '199', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '0', '9');
INSERT INTO `copy` VALUES ('215', '199', 'Microsoft Windows ', 'https://baike.baidu.com/item/Microsoft', '37', '54');
INSERT INTO `copy` VALUES ('216', '199', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '0', '9');
INSERT INTO `copy` VALUES ('217', '199', 'icrosoft ', 'https://baike.baidu.com/item/Microsoft', '1', '9');
INSERT INTO `copy` VALUES ('218', '200', 'Microsoft Office', 'https://baike.baidu.com/item/Office', '17', '32');
INSERT INTO `copy` VALUES ('219', '200', 'icrosoft Office', 'https://baike.baidu.com/item/Office', '18', '32');
INSERT INTO `copy` VALUES ('220', '200', 'Microsoft Office', 'https://baike.baidu.com/item/Office', '17', '32');
INSERT INTO `copy` VALUES ('221', '200', 'icrosoft Office', 'https://baike.baidu.com/item/Office', '18', '32');
INSERT INTO `copy` VALUES ('222', '200', 'Microsoft Office', 'https://baike.baidu.com/item/Office', '17', '32');
INSERT INTO `copy` VALUES ('223', '200', 'PowerPoint', 'https://baike.baidu.com/item/Office', '336', '345');
INSERT INTO `copy` VALUES ('224', '200', 'icrosoft Office', 'https://baike.baidu.com/item/Office', '18', '32');
INSERT INTO `copy` VALUES ('225', '200', 'PowerPoint', 'https://baike.baidu.com/item/Office', '336', '345');
INSERT INTO `copy` VALUES ('226', '200', 'Microsoft Office', 'https://baike.baidu.com/item/Office', '17', '32');
INSERT INTO `copy` VALUES ('227', '200', 'Microsoft Office', 'https://baike.baidu.com/item/Office', '17', '32');
INSERT INTO `copy` VALUES ('228', '200', 'Microsoft Office', 'https://baike.baidu.com/item/Office', '17', '32');
INSERT INTO `copy` VALUES ('229', '200', 'icrosoft Office', 'https://baike.baidu.com/item/Office', '18', '32');
INSERT INTO `copy` VALUES ('230', '200', 'Microsoft Office', 'https://baike.baidu.com/item/Office', '17', '32');
INSERT INTO `copy` VALUES ('231', '200', 'icrosoft Office', 'https://baike.baidu.com/item/Office', '18', '32');
INSERT INTO `copy` VALUES ('232', '200', 'Microsoft Office', 'https://baike.baidu.com/item/Office', '17', '32');
INSERT INTO `copy` VALUES ('233', '200', 'icrosoft Office', 'https://baike.baidu.com/item/Office', '18', '32');
INSERT INTO `copy` VALUES ('234', '200', 'Microsoft Office', 'https://baike.baidu.com/item/Office', '17', '32');
INSERT INTO `copy` VALUES ('235', '200', 'icrosoft Office', 'https://baike.baidu.com/item/Office', '18', '32');
INSERT INTO `copy` VALUES ('236', '200', 'Microsoft Office', 'https://baike.baidu.com/item/Office', '17', '32');
INSERT INTO `copy` VALUES ('237', '200', 'icrosoft Office', 'https://baike.baidu.com/item/Office', '18', '32');
INSERT INTO `copy` VALUES ('238', '200', 'Microsoft ', 'https://baike.baidu.com/item/Office', '17', '26');
INSERT INTO `copy` VALUES ('239', '200', 'Microsoft ', 'https://baike.baidu.com/item/Office', '17', '26');
INSERT INTO `copy` VALUES ('240', '200', 'icrosoft ', 'https://baike.baidu.com/item/Office', '18', '26');
INSERT INTO `copy` VALUES ('241', '200', 'Microsoft Office', 'https://baike.baidu.com/item/Office', '17', '32');
INSERT INTO `copy` VALUES ('242', '200', 'icrosoft Office', 'https://baike.baidu.com/item/Office', '18', '32');
INSERT INTO `copy` VALUES ('243', '200', 'Microsoft ', 'https://baike.baidu.com/item/Office', '17', '26');
INSERT INTO `copy` VALUES ('244', '200', 'icrosoft ', 'https://baike.baidu.com/item/Office', '18', '26');
INSERT INTO `copy` VALUES ('245', '200', 'icrosoft Office', 'https://baike.baidu.com/item/Office', '18', '32');
INSERT INTO `copy` VALUES ('246', '200', 'Microsoft ', 'https://baike.baidu.com/item/Office', '17', '26');
INSERT INTO `copy` VALUES ('247', '200', 'icrosoft ', 'https://baike.baidu.com/item/Office', '18', '26');
INSERT INTO `copy` VALUES ('248', '200', 'Microsoft ', 'https://baike.baidu.com/item/Office', '17', '26');
INSERT INTO `copy` VALUES ('249', '200', 'icrosoft ', 'https://baike.baidu.com/item/Office', '18', '26');
INSERT INTO `copy` VALUES ('250', '200', 'Microsoft ', 'https://baike.baidu.com/item/Office', '17', '26');
INSERT INTO `copy` VALUES ('251', '200', 'Microsoft ', 'https://baike.baidu.com/item/Office', '17', '26');
INSERT INTO `copy` VALUES ('252', '200', 'icrosoft ', 'https://baike.baidu.com/item/Office', '18', '26');
INSERT INTO `copy` VALUES ('253', '200', 'Microsoft ', 'https://baike.baidu.com/item/Office', '17', '26');
INSERT INTO `copy` VALUES ('254', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('255', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('256', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('257', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('258', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('259', '200', 'icrosoft ', 'https://baike.baidu.com/item/Microsoft', '18', '26');
INSERT INTO `copy` VALUES ('260', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('261', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('262', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('263', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('264', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('265', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('266', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('267', '200', 'icrosoft ', 'https://baike.baidu.com/item/Microsoft', '18', '26');
INSERT INTO `copy` VALUES ('268', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('269', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('270', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('271', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('272', '200', 'Microsoft W', 'https://baike.baidu.com/item/Microsoft', '1434', '1444');
INSERT INTO `copy` VALUES ('273', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('274', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('275', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('276', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('277', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('278', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('279', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('280', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('281', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('282', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('283', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('284', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('285', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('286', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('287', '200', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '17', '26');
INSERT INTO `copy` VALUES ('288', '201', 'WPS Office是由', 'https://baike.baidu.com/item/WPS', '0', '11');
INSERT INTO `copy` VALUES ('289', '201', '金山软件股份有限公司自主研发的一款', 'https://baike.baidu.com/item/WPS', '12', '28');
INSERT INTO `copy` VALUES ('290', '201', '办公软件套装，可以实现', 'https://baike.baidu.com/item/WPS', '29', '39');
INSERT INTO `copy` VALUES ('291', '201', '办公软件最常用的文字、表格、演示等多种功能。具有内存占用低、运行速度快、体积小巧、强大插件平台支持、免费提供海量在线存储空间及', 'https://baike.baidu.com/item/WPS', '40', '102');
INSERT INTO `copy` VALUES ('292', '203', 'Windows ', 'https://baike.baidu.com/item/Windows', '365', '372');
INSERT INTO `copy` VALUES ('293', '205', '一定方式储存在一起、能与多个用户', 'https://baike.baidu.com/item/数据库', '15', '30');
INSERT INTO `copy` VALUES ('294', '205', '共享、具有尽可能小的', 'https://baike.baidu.com/item/数据库', '31', '40');
INSERT INTO `copy` VALUES ('295', '205', '冗余度、与应用程序彼此独立的数据', 'https://baike.baidu.com/item/数据库', '41', '56');
INSERT INTO `copy` VALUES ('296', '205', '的处所，用户可以对文件中的数据进行新增、截取、更新、删除等操作。', 'https://baike.baidu.com/item/数据库', '118', '149');
INSERT INTO `copy` VALUES ('297', '208', '解决大规模数据集合多重数据种类带来的挑战，尤其是大数据应用难题', 'https://baike.baidu.com/item/NoSQL', '93', '123');
INSERT INTO `copy` VALUES ('298', '208', '发展。NoSQL', 'https://baike.baidu.com/item/NoSQL', '134', '141');
INSERT INTO `copy` VALUES ('299', '210', 'Microsoft', 'https://baike.baidu.com/item/Microsoft', '16', '24');
INSERT INTO `copy` VALUES ('300', '210', 'Microsoft', 'https://baike.baidu.com/item/Microsoft', '16', '24');
INSERT INTO `copy` VALUES ('301', '210', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '124', '131');
INSERT INTO `copy` VALUES ('302', '210', 'Microsoft', 'https://baike.baidu.com/item/Microsoft', '16', '24');
INSERT INTO `copy` VALUES ('303', '210', 'Microsoft', 'https://baike.baidu.com/item/Microsoft', '16', '24');
INSERT INTO `copy` VALUES ('304', '210', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '124', '131');
INSERT INTO `copy` VALUES ('305', '210', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '124', '131');
INSERT INTO `copy` VALUES ('306', '210', 'Microsoft ', 'https://baike.baidu.com/item/Microsoft', '298', '307');
INSERT INTO `copy` VALUES ('307', '210', 'Windows ', 'https://baike.baidu.com/item/Microsoft', '124', '131');
INSERT INTO `copy` VALUES ('308', '210', 'icrosoft ', 'https://baike.baidu.com/item/Microsoft', '299', '307');
INSERT INTO `copy` VALUES ('309', '210', 'Microsoft', 'https://baike.baidu.com/item/Windows', '16', '24');
INSERT INTO `copy` VALUES ('310', '210', 'Microsoft', 'https://baike.baidu.com/item/Windows', '16', '24');
INSERT INTO `copy` VALUES ('311', '210', 'Microsoft', 'https://baike.baidu.com/item/Windows', '16', '24');
INSERT INTO `copy` VALUES ('312', '210', 'Windows ', 'https://baike.baidu.com/item/Windows', '124', '131');
INSERT INTO `copy` VALUES ('313', '210', 'Windows ', 'https://baike.baidu.com/item/Windows', '124', '131');
INSERT INTO `copy` VALUES ('314', '210', 'Microsoft ', 'https://baike.baidu.com/item/Windows', '298', '307');
INSERT INTO `copy` VALUES ('315', '210', 'icrosoft ', 'https://baike.baidu.com/item/Windows', '299', '307');
INSERT INTO `copy` VALUES ('316', '210', 'Microsoft', 'https://baike.baidu.com/item/据库', '16', '24');
INSERT INTO `copy` VALUES ('317', '210', 'Microsoft', 'https://baike.baidu.com/item/据库', '16', '24');
INSERT INTO `copy` VALUES ('318', '210', 'Microsoft', 'https://baike.baidu.com/item/据库', '16', '24');
INSERT INTO `copy` VALUES ('319', '210', 'Windows ', 'https://baike.baidu.com/item/据库', '124', '131');
INSERT INTO `copy` VALUES ('320', '210', 'Windows ', 'https://baike.baidu.com/item/据库', '124', '131');
INSERT INTO `copy` VALUES ('321', '210', 'Microsoft ', 'https://baike.baidu.com/item/据库', '298', '307');
INSERT INTO `copy` VALUES ('322', '210', 'icrosoft ', 'https://baike.baidu.com/item/据库', '299', '307');
INSERT INTO `copy` VALUES ('323', '211', '系型数据库管理系统', 'https://baike.baidu.com/item/MySQL', '35', '43');
INSERT INTO `copy` VALUES ('324', '211', '目前属于 Oracle ', 'https://baike.baidu.com/item/MySQL', '45', '56');
INSERT INTO `copy` VALUES ('325', '217', 'computer', 'https://baike.baidu.com/item/计算机', '6', '13');
INSERT INTO `copy` VALUES ('326', '217', 'computer', 'https://baike.baidu.com/item/算机', '6', '13');
INSERT INTO `copy` VALUES ('327', '220', '际标准化组织（ISO）', 'https://baike.baidu.com/item/OSI', '117', '127');
INSERT INTO `copy` VALUES ('328', '220', 'pen System Interconnection', 'https://baike.baidu.com/item/OSI', '151', '176');
INSERT INTO `copy` VALUES ('329', '220', '数据链路层、网络层、', 'https://baike.baidu.com/item/OSI', '553', '562');
INSERT INTO `copy` VALUES ('330', '222', '信号进行再生整形放大，以扩大网络的传输距离，同时把所有', 'https://baike.baidu.com/item/集线器', '116', '142');
INSERT INTO `copy` VALUES ('331', '222', '节点集中在以它为中心的节点上。', 'https://baike.baidu.com/item/集线器', '143', '157');
INSERT INTO `copy` VALUES ('332', '222', '网桥（Bridge）', 'https://baike.baidu.com/item/网桥', '375', '384');
INSERT INTO `copy` VALUES ('333', '222', '网桥（Bridge）', 'https://baike.baidu.com/item/算机', '375', '384');
INSERT INTO `copy` VALUES ('334', '224', 'P地址是指互联网协议地址（', 'https://baike.baidu.com/item/地址', '3', '15');
INSERT INTO `copy` VALUES ('335', '224', 'Internet Protocol Address', 'https://baike.baidu.com/item/地址', '16', '40');
INSERT INTO `copy` VALUES ('336', '224', 'P地址是指互联网协议地址（', 'https://baike.baidu.com/item/相当于', '3', '15');
INSERT INTO `copy` VALUES ('337', '224', 'Internet Protocol Address', 'https://baike.baidu.com/item/相当于', '16', '40');
INSERT INTO `copy` VALUES ('338', '224', 'P地址是指互联网协议地址（', 'https://baike.baidu.com/item/ 网络', '3', '15');
INSERT INTO `copy` VALUES ('339', '224', 'Internet Protocol Address', 'https://baike.baidu.com/item/ 网络', '16', '40');
INSERT INTO `copy` VALUES ('340', '224', '互联网协议地址（', 'https://baike.baidu.com/item/IP', '8', '15');
INSERT INTO `copy` VALUES ('341', '224', 'Internet Protocol Address', 'https://baike.baidu.com/item/IP', '16', '40');
INSERT INTO `copy` VALUES ('342', '224', 'Internet', 'https://baike.baidu.com/item/互联网', '16', '23');
INSERT INTO `copy` VALUES ('343', '224', 'Internet', 'https://baike.baidu.com/item/一台', '16', '23');
INSERT INTO `copy` VALUES ('344', '224', 'P地址是指互联网协议地址（', 'https://baike.baidu.com/item/IP地址', '3', '15');
INSERT INTO `copy` VALUES ('345', '224', 'Internet Protocol Address', 'https://baike.baidu.com/item/IP地址', '16', '40');
INSERT INTO `copy` VALUES ('346', '224', 'IP协议提供的一种统一的地址格式，', 'https://baike.baidu.com/item/IP地址', '48', '64');
INSERT INTO `copy` VALUES ('347', '224', '上的每一个网络和每一台主机分配一个逻辑地址，以', 'https://baike.baidu.com/item/IP地址', '71', '93');
INSERT INTO `copy` VALUES ('348', '224', '物理地址的差异。', 'https://baike.baidu.com/item/IP地址', '96', '103');
INSERT INTO `copy` VALUES ('349', '225', 'omain Name System，', 'https://baike.baidu.com/item/域名', '6', '23');
INSERT INTO `copy` VALUES ('350', '226', 'orld Wide Web', 'https://baike.baidu.com/item/WWW', '5', '17');
INSERT INTO `copy` VALUES ('351', '229', 'Domain Name System', 'https://baike.baidu.com/item/DNS', '9', '26');
INSERT INTO `copy` VALUES ('352', '229', 'Domain Name', 'https://baike.baidu.com/item/域名', '9', '19');
INSERT INTO `copy` VALUES ('353', '230', '动态主机设置协议（', 'https://baike.baidu.com/item/DHCP', '0', '8');
INSERT INTO `copy` VALUES ('354', '230', 'Dynamic Host Configuration Protocol，', 'https://baike.baidu.com/item/DHCP', '9', '44');
INSERT INTO `copy` VALUES ('355', '230', '于内部网或网络服务供应商自动分配', 'https://baike.baidu.com/item/DHCP', '79', '94');
INSERT INTO `copy` VALUES ('356', '230', '管理员作为对所有计算机', 'https://baike.baidu.com/item/DHCP', '109', '119');
INSERT INTO `copy` VALUES ('357', '230', '动态主机设置协议（', 'https://baike.baidu.com/item/ 协议', '0', '8');
INSERT INTO `copy` VALUES ('358', '230', 'Dynamic Host Configuration Protocol，', 'https://baike.baidu.com/item/ 协议', '9', '44');
INSERT INTO `copy` VALUES ('359', '230', '于内部网或网络服务供应商自动分配', 'https://baike.baidu.com/item/ 协议', '79', '94');
INSERT INTO `copy` VALUES ('360', '230', '管理员作为对所有计算机', 'https://baike.baidu.com/item/ 协议', '109', '119');
INSERT INTO `copy` VALUES ('361', '230', ' Protocol', 'https://baike.baidu.com/item/IP地址', '35', '43');
INSERT INTO `copy` VALUES ('362', '230', ' Protocol', 'https://baike.baidu.com/item/用于', '35', '43');
INSERT INTO `copy` VALUES ('363', '240', '重要组成部分，主要', 'https://baike.baidu.com/item/工业', '46', '54');
INSERT INTO `copy` VALUES ('364', '242', '2015年8月29日，十二届全国人大常委会十六次会议表决通过刑法修正案（九）。', 'https://baike.baidu.com/item/刑法', '0', '38');
INSERT INTO `copy` VALUES ('365', '242', '修改后的刑法自2015年11月1日开始施行。这也是继1997年全面修订刑法后通过的第九个刑法修正案。', 'https://baike.baidu.com/item/刑法', '39', '88');
INSERT INTO `copy` VALUES ('366', '242', '有广义与狭义之分。广义刑法是一切刑事法律规范的总称，狭义刑法仅指刑法典，在我国即《', 'https://baike.baidu.com/item/刑法', '108', '148');
INSERT INTO `copy` VALUES ('367', '242', '中华人民共和国刑法》。', 'https://baike.baidu.com/item/刑法', '149', '159');
INSERT INTO `copy` VALUES ('368', '242', '与广义刑法、狭义刑法相联系的，刑法还可区分为普通刑法和特别刑法。普通刑法指具有普遍使用效力的刑法，实际上即指刑法典。特别刑法指仅使用于特定的人、时、地、事（犯罪）的刑法。在我国，也叫', 'https://baike.baidu.com/item/刑法', '160', '250');
INSERT INTO `copy` VALUES ('369', '243', '全国人民代表大会常务委员会', 'https://baike.baidu.com/item/全国人民代表大会常务委员会', '13', '25');
INSERT INTO `copy` VALUES ('370', '243', '全国人民代表大会常务委员会', 'https://baike.baidu.com/item/全国人民代表大会常务委员会', '13', '25');
INSERT INTO `copy` VALUES ('371', '243', '全国人民代表大会常务委员会', 'https://baike.baidu.com/item/护国', '13', '25');
INSERT INTO `copy` VALUES ('372', '243', '全国人民代表大会常务委员会', 'https://baike.baidu.com/item/护国', '13', '25');
INSERT INTO `copy` VALUES ('373', '244', '中华人民共和国国家安全法', 'https://baike.baidu.com/item/安全法', '0', '11');
INSERT INTO `copy` VALUES ('374', '244', '中华人民共和国国家安全法', 'https://baike.baidu.com/item/安全法', '0', '11');
INSERT INTO `copy` VALUES ('375', '245', '全国人民代表大会常务委员会', 'https://baike.baidu.com/item/人大常委会', '15', '27');
INSERT INTO `copy` VALUES ('376', '245', '全国人民代表大会常务委员会', 'https://baike.baidu.com/item/人大常委会', '15', '27');
INSERT INTO `copy` VALUES ('377', '245', '全国人民代表大会常务委员会', 'https://baike.baidu.com/item/全国人大', '15', '27');
INSERT INTO `copy` VALUES ('378', '245', '全国人民代表大会', 'https://baike.baidu.com/item/全国人大', '15', '22');
INSERT INTO `copy` VALUES ('379', '245', '全国人民代表大会常务委员会', 'https://baike.baidu.com/item/全国人大常委会', '15', '27');
INSERT INTO `copy` VALUES ('380', '245', '全国人民代表大会常务委员会', 'https://baike.baidu.com/item/全国人大常委会', '15', '27');
INSERT INTO `copy` VALUES ('381', '249', '2015年7月1日，第十二届全国人民代表大会常务委员会第十五次会议通过新的国家安全法。国家主席习近平签署第29号主席令予以公布。法律对政治安全、国土安全、军事安全、文化安全、科技安全等11个领域的国家安全任务进行了明确，共7章84条，自2015年7月1日起施行。', 'https://baike.baidu.com/item/安全法', '0', '130');
INSERT INTO `copy` VALUES ('382', '249', '华人民共和国国家安全法，是为了维护国家安全，保卫人民民主专政的政权和中国特色社会主义制度，保护人民的根本利益，保障改革开放和社会主义现代化建设的顺利进行，实现中华民族伟大复兴，根据《', 'https://baike.baidu.com/item/安全法', '132', '222');
INSERT INTO `copy` VALUES ('383', '249', '中华人民共和国宪法》，制定的法规。', 'https://baike.baidu.com/item/安全法', '223', '239');
INSERT INTO `copy` VALUES ('384', '250', '全国人民代表大会常务委员会', 'https://baike.baidu.com/item/全国人民代表大会常务委员会', '14', '26');
INSERT INTO `copy` VALUES ('385', '250', '全国人民代表大会常务委员会', 'https://baike.baidu.com/item/全国人民代表大会常务委员会', '14', '26');
